### ISSUE TITLE
Fix for ffmpeg thread queue size warning

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [blha303/iviewdl#11]
Hi

I noticed that I was getting warnings when downloading some programs, because the ffmpeg thread_queue_size seemed to be too low

So, after some messing around, I think a possible fix is to add the 

-thread_queue_size as the first argument to ffmpeg and set the value to 512

I tried values like 64 and 256 but still got the warning, but setting it to 512 seemed to get rid of the warnings.

```
def get_download_cmd(urls, filename=None):
    out = ["ffmpeg"]
    out += ["-thread_queue_size" , "512"]
... etc
```

BTW. I tied putting this option  a bit further down the list of arguments, but ffmpeg gave an error saying that this option needed to be put before the input stream to which it related, hence I just put it as the first argument

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```
