### ISSUE TITLE
Go further back than 4 shows?

### ISSUE THREAD

**Issue by lincalinca** [blha303/iviewdl#13]
I can't seem to find anything more than 4 episodes back, because of the selection options, yet when I look on iview, I can see the episodes.

**Comment by rogerclarkmelbourne** [comment]
Interesting ...

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```

**Comment by blha303** [comment]
Sorry, I was a little hasty. I've written a wrapper for youtube-dl that takes an iview url and, if it's a series, downloads all episodes, or if it's an episode share url it'll download that one episode. https://github.com/blha303/iviewdl/blob/master/new_iviewdl.py

**Comment by rogerclarkmelbourne** [comment]
OK

It would still be better if there was a command line method to get a list etc, so it could be scripted.

I'll take a look at your new version.

**Comment by blha303** [comment]
It would be easy to modify the new script to suit needs, it's just a frontend for youtube-dl.

**Comment by rogerclarkmelbourne** [comment]
OK.. Thanks

**Comment by lincalinca** [comment]
Thanks @blha303 that's really neat
I'm always just trying to grab it all anyway :)

**Comment by lincalinca** [comment]
umm... what do I need to do to run this?
do I need to overwrite the existing iviewdl python file?

**Comment by blha303** [comment]
Install ffmpeg and youtube-dl with pip, then run the script directly `python new_iview.py`

**Comment by rogerclarkmelbourne** [comment]
BTW. 
You may need to install setup tools (via pip)
My latest Linux (Mint) installation didnt include them as part of its default Python installation.

**Comment by blha303** [comment]
The script doesn't depend on the youtube-dl CLI wrapper so setuptools isn't required, and I just realised ffmpeg isn't a python package, it'll have to be installed through the system package manager or by downloading a Windows binary if that's the case. https://ffmpeg.zeranoe.com/builds/

**Comment by rogerclarkmelbourne** [comment]
OK. The iviewdl did ;-)

I just installed ffmpeg using apt-get
