### ISSUE TITLE
Problems with setuptools on some systems

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [blha303/iviewdl#14]
The Readme should probably be updated note that python setuptools  are not installed by default on some systems.

My old version of Linux Mate had them installed but the latest version doesn't

So I had to install them via pip

`pip install setuptools `

However also, on the latest Linux Mate, the path to the the installer doesn't seem to make iviewdl available from the console.

I ended up cloning the repo to my hone directory and now run python, passing iviewdl and the search string as arguments

i.e 

`python iviewdl news`

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```

**Comment by blha303** [comment]
Sorry, I was a little hasty. I've written a wrapper for youtube-dl that takes an iview url and, if it's a series, downloads all episodes, or if it's an episode share url it'll download that one episode. https://github.com/blha303/iviewdl/blob/master/new_iviewdl.py
