### ISSUE TITLE
Incomplete episode list

### ISSUE THREAD

**Issue by gjb** [blha303/iviewdl#15]
When I run `iviewdl Killing`, I see:
~~~
    0: Killing Eve Series 1 Ep 2 I'll Deal With Him Later
    1: Killing Eve Series 1 Ep 5 I Have A Thing About Bathrooms
    2: Killing Eve Series 1 Ep 7 I Don't Want To Be Free
~~~
This is what am offered by the iView app on my crappy set top box. But, on the ABC website, episodes 1 through to 8 are all available. The episodes that are offered above all download perfectly, it's just that I can't find a way to access the other 5 episodes.

Is there any chance that there might be a simple fix to get the rest?

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```

**Comment by blha303** [comment]
Sorry, I was a little hasty. I've written a wrapper for youtube-dl that takes an iview url and, if it's a series, downloads all episodes, or if it's an episode share url it'll download that one episode. https://github.com/blha303/iviewdl/blob/master/new_iviewdl.py
