### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by rmit-s3644396-andrew-moran** [blha303/iviewdl#16]
I've got the latest release, and while the search function works fine, I can't actually download a video:

$ iviewdl Tonightly
0: Tonightly With Tom Ballard The Best Ever
1: Tonightly With Tom Ballard 6/9/2018
2: Tonightly With Tom Ballard 5/9/2018
enter your choice: 2
Downloading Tonightly With Tom Ballard 5/9/2018
Traceback (most recent call last):
  File "/usr/local/bin/iviewdl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/iviewdl/iviewdl.py", line 129, in main
    data = get_stream_urls(requests.get("http://iview.abc.net.au/api/" + result["href"]).json())
  File "/usr/local/lib/python3.7/site-packages/iviewdl/iviewdl.py", line 62, in get_stream_urls
    out["rating"] = p["hls-plus"] + generate_secret(data["episodeHouseNumber"])
  File "/usr/local/lib/python3.7/site-packages/iviewdl/iviewdl.py", line 39, in generate_secret
    message = bytes(urlparam)
TypeError: string argument without an encoding

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```

**Comment by blha303** [comment]
Sorry, I was a little hasty. I've written a wrapper for youtube-dl that takes an iview url and, if it's a series, downloads all episodes, or if it's an episode share url it'll download that one episode. https://github.com/blha303/iviewdl/blob/master/new_iviewdl.py
