### ISSUE TITLE
Select from multiple choices

### ISSUE THREAD

**Issue by denis9918** [blha303/iviewdl#2]
Hi Steven,
I installed using pip3..
pip3 install git+https://github.com/blha303/iviewdl

Using; $ iviewdl micallef
gives;
0: Shaun Micallef's MAD AS HELL Series 7 Ep 5
1: Shaun Micallef's MAD AS HELL Series 7 Ep 4
2: Shaun Micallef's MAD AS HELL Series 7 Ep 3

but I can't figure out how to download No2.
I've tried every variation of;
$ iviewdl micallef --selection 2
that I can think of to no avail.

Pretty sure I'm missing something simple, but I'd appreciate any help .

Regards
Denis

**Comment by blha303** [comment]
Thank you for reporting this, I'll fix it now.
