### ISSUE TITLE
"--selection 0" reprints episode list instead of downloading first episode

### ISSUE THREAD

**Issue by catgotchaT** [blha303/iviewdl#4]
Hi, 
I notice the --selection arguement not working as it should be, specifically "--selection 0" just reprints the episode list instead of downloading the first episode in the list.

I believe the issue lies at line 70 in iviewdl.py. 
The **parser.add_argument** is adding **--selection** as an argument, regardless of if the user specifies that argument or not. 

So if a user _does not_ specify --selection [n], it's actually set to the python null value "None".

Consequently on line 70 `if not args.selection`  does not work correctly because it _has_ been set, just to "None".

I believe line 70 should be something like the following which works for me:

`if args.selection is None:
`

Existing code excerpt for reference:

```
def main():
    from argparse import ArgumentParser
    import subprocess
    parser = ArgumentParser()
    parser.add_argument("search")
    parser.add_argument("--selection", help="Number of video to get", type=int)
    parser.add_argument("--filename")
    args = parser.parse_args()
    results = search(args.search)
    if len(results) > 1:
        if not args.selection:
   ..........
```

I can do a pull request if you like but as it's just one line...

**Comment by blha303** [comment]
I'll admit, I was rushed when I made this and gave it only the barest amount of testing. I checked that it downloaded the episode I wanted and left it at that. Thanks for reporting this.
