### ISSUE TITLE
HTTP error 400 Bad Request

### ISSUE THREAD

**Issue by jameselks** [blha303/iviewdl#9]
Fresh install of Ubuntu 16.04 on Virtualbox. I can see the episodes (although not *all* the episodes listed on iView) but when I select one for download:

```
[http @ 0x16c1d20] HTTP error 400 Bad Request
http://iviewum-vh.akamaihd.net/i/playback/_definst_/_video/cat/catalyst_17_07_20180122172128_,650000,500000,220000,.mp4.csmil/master.m3u8?hdneast=1519030278~exp=1519040277~acl=/*~hmac=878d5bea27b0391d0e4f4701d6e9e0fe4733f70dbc81f8c33c25e30f2114ea73: Server returned 400 Bad Request
```

**Comment by blha303** [comment]
I noticed this a few weeks ago. I haven't had the time to figure out why it's doing this, I fiddled around a little bit but it seems they've changed the way the system works.

**Comment by rogerclarkmelbourne** [comment]
I've not seen this recently. Perhaps this issue should be closed

**Comment by blha303** [comment]
project deprecated, closing all issues as won't fix

Get the url from iview using the Share button under an episode, copy the link
```bash
$ pip install youtube-dl 
$ youtube-dl https://iview.abc.net.au/show/shaun-micallefs-mad-as-hell/series/9/video/LE1814V001S00
```
